### ISSUE TITLE
file output exception

### ISSUE THREAD

**Issue by thequinto** [newsapps/beeswithmachineguns#143]
Hi, I'm trying to use the file output option, but open() seems to be throwing an exception.  Has anyone else encountered this issue?  Using Python 2.7.10.  With some trace statements, it's calling with the arguments: open('results.csv', 'w', {'newline':'','encoding':'utf-8'})

Traceback (most recent call last):
  File "/usr/local/bin/bees", line 5, in <module>
    main.main()
  File "/usr/local/lib/python2.7/site-packages/beeswithmachineguns/main.py", line 173, in main
    parse_options()
  File "/usr/local/lib/python2.7/site-packages/beeswithmachineguns/main.py", line 166, in parse_options
    bees.attack(options.url, options.number, options.concurrent, **additional_options)
  File "/usr/local/lib/python2.7/site-packages/beeswithmachineguns/bees.py", line 728, in attack
    summarized_results = _summarize_results(results, params, csv_filename)
  File "/usr/local/lib/python2.7/site-packages/beeswithmachineguns/bees.py", line 494, in _summarize_results
    _create_request_time_cdf_csv(results, summarized_results['complete_bees_params'], summarized_results['request_time_cdf'], csv_filename)
  File "/usr/local/lib/python2.7/site-packages/beeswithmachineguns/bees.py", line 510, in _create_request_time_cdf_csv
    with io.open(csv_filename, openmode, openkwargs) as stream:
TypeError: an integer is required

**Comment by tecnobrat** [comment]
I am also encountering this issue.

**Comment by carlislk** [comment]
I am experiencing this same issue. Any updates?

**Comment by jmart1** [comment]
I also have this.  Has anyone resolved this?

**Comment by aaronArinder** [comment]
The function referenced by the original err now looks like this:

```py
def _create_request_time_cdf_csv(results, complete_bees_params, request_time_cdf, csv_filename):
    if csv_filename:
        # csv requires files in text-mode with newlines='' in python3
        # see http://python3porting.com/problems.html#csv-api-changes
        openmode = IS_PY2 and 'w' or 'wt'
        openkwargs = IS_PY2 and {} or {'encoding': 'utf-8', 'newline': ''}
        with open(csv_filename, openmode, openkwargs) as stream:
            writer = csv.writer(stream)
            header = ["% faster than", "all bees [ms]"]
            for p in complete_bees_params:
                header.append("bee %(instance_id)s [ms]" % p)
            writer.writerow(header)
            for i in range(100):
                row = [i, request_time_cdf[i]] if i < len(request_time_cdf) else [i,float("inf")]
                for r in results:
                    if r is not None:
                    	row.append(r['request_time_cdf'][i]["Time in ms"])
                writer.writerow(row)
```

`open(..)`'s third arg [needs to be a number](https://docs.python.org/2/library/functions.html#open), to set the buffer size used.

```
open(name[, mode[, buffering]])
...
The optional buffering argument specifies the file’s desired buffer size: 0 means unbuffered,
 1 means line buffered, any other positive value means use a buffer of (approximately) that
 size (in bytes). A negative buffering means to use the system default, which is usually line
 buffered for tty devices and fully buffered for other files. If omitted, the system default is
 used. 
```
