### ISSUE TITLE
Unable to change from default VPC

### ISSUE THREAD

**Issue by lgenet** [newsapps/beeswithmachineguns#144]
Good day,

I am in a possibly weird use case.  I do not have a default VPC in my region (it was deleted)  I appear to be getting an error from ec2 saying that the VPCIdNotSpecified.  I have failed to find a way to specify a VPC that is not the default.  I found that there is a subnet flag, but every time I try to use it I get an error about unrecognized flag.  

Is it possible to modify bees to allow us to have them spin up in a VPC that is not the default VPC?

Thank you for your time,

Logan

Error:
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>VPCIdNotSpecified</Code><Message>No default VPC for this user</Message></Error></Errors><RequestID>1b7190ca-1510-42b3-8714-9314e8c7d280</RequestID></Response>

**Comment by brianpatrickreavey** [comment]
Hi Logan,

I know in our setup, we do not have to specify anything other than the subnet.  We do have a default VPC, but that is not the VPC we are using for our deployment.

When we've discussed the 'default VPC' with our AWS support the bad, they indicated that deleting it would be "a very bad thing" and that all sorts of things would stop working.   I think their technical support can recreate this for you.

That being said, did your error message above indicate a line number or anything where the error occurred?

-- Brian

**Comment by lgenet** [comment]
@brianpatrickreavey Thank you for the response,

My company's security group flagged having unused VPCs as an issue, but we might have to ask AWS to recreate them in the short term if we can not find another solution.  It does appear that there is a -v command somewhere that my bees installation claims is not a valid flag 
`Usage: 
bees COMMAND [options]

Bees with Machine Guns

A utility for arming (creating) many bees (small EC2 instances) to attack
(load test) targets (web applications).

commands:
  up      Start a batch of load testing servers.
  attack  Begin the attack on a specific url.
  down    Shutdown and deactivate the load testing servers.
  report  Report the status of the load testing servers.
    

bees: error: no such option: -v`

However I am not sure how helpful that would be in the end.  I think we might have to go with the recreating of the default VPC for the bees to spin up into for a short period of time.

Here is the Full Error Stack I get when trying to run my bees:
`Traceback (most recent call last):
  File "/usr/local/bin/bees", line 5, in <module>
    main.main()
  File "/usr/local/lib/python2.7/site-packages/beeswithmachineguns/main.py", line 127, in main
    parse_options()
  File "/usr/local/lib/python2.7/site-packages/beeswithmachineguns/main.py", line 111, in parse_options
    bees.up(options.servers, options.group, options.zone, options.instance, options.login, options.key)
  File "/usr/local/lib/python2.7/site-packages/beeswithmachineguns/bees.py", line 104, in up
    placement=zone)
  File "/usr/local/lib/python2.7/site-packages/boto/ec2/connection.py", line 973, in run_instances
    verb='POST')
  File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 1208, in get_object
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>VPCIdNotSpecified</Code><Message>No default VPC for this user</Message></Error></Errors><RequestID>e7f7988e-bd15-46c5-8ccd-ae6d6157198e</RequestID></Response>`

**Comment by brianpatrickreavey** [comment]
Are you specifying a subnet via the `--subnet=subnet-12345678` flag?  What does your calling command look like?

**Comment by lgenet** [comment]
I just tried it with that flag and got the same message (only substitute -v for --subnet) 
This is my calling command:

`bees up -s 4 -g securityGroupName -k myPem --subnet=subnet-2337b754`

**Comment by brianpatrickreavey** [comment]
The only difference that we have in our configuration is that we're specifying the AZ as well:

`bees up -s 5 -g bees -z us-east-1b -i ami-xxxxxxxx -t m4.large -l ec2-user -k keyname --subnet=subnet-xxxxxxxx`

the `-z <zone>` should be whatever AZ the subnet specified is in.  Looking at the argument parsing, its setting a default zone of `us-east-1d` for some reason.

**Comment by kylebechtel77** [comment]
@brianpatrickreavey I work with @lgenet and we are still trying to solve this issue. We have had AWS add back our default vpc, I have downloaded your source python code and I'm running it and debugging it locally, just so I can be sure I'm up to date with your latest version.  We are now we are trying to run this command:

`bees up -g bees -z us-west-2b -k keyname`

and are getting this error: 

Connecting to the hive.
GroupId found: bees
Placement: us-west-2b
Attempting to call up 5 bees.
('Unable to call bees:', '')

**Comment by kylebechtel77** [comment]
tracking it a bit further I get:

`Connecting to the hive.
GroupId found: bees
Placement: us-west-2b
Attempting to call up 5 bees.
('Unable to call bees:', u'Value () for parameter groupId is invalid. The value cannot be empty')`

Even though it says it just found the groupId. Any idea as to whats going on here?

**Comment by kylebechtel77** [comment]
After modifying our security group we are now getting an error saying the ami is not valid. @brianpatrickreavey Could you copy your ami for bees to the us-west-2 region please?

**Comment by brianpatrickreavey** [comment]
Hi @kylebechtel77  , what is the ami that you are using?  I believe you can use any AWS linux AMI and it ought to work, but I will check with one of my coworkers in the morning.

What AMI are you attempting to use?

**Comment by mudrii** [comment]
I think bees as of now works only with PV type VM and make sure to configure no VPC security group
for us-west-2b try to use Amazon Linux AMI 2016.03.1 (PV) - ami-eff1028f

**Comment by thequinto** [comment]
@lgenet did you make sure you pulled the latest source code from GitHub?  I had the same issue using the -v flag from the yum repo's copy.
