### ISSUE TITLE
Authentication error when running bees attack

### ISSUE THREAD

**Issue by nmallya** [newsapps/beeswithmachineguns#145]
I keep getting an authentication error when i try to run  bees attack ...
I saw another similar issue that was posted and closed with no indication of resolution.  I just installed python 2.7, beeswithmachineguns etc on a new machine

Please let me know if anyone has resolved this issue. I can see the bee instances created in AWS

$ bees attack -n 1 -c 1 -u http://www.*******.***
Read 1 bees from the roster.
Connecting to the hive.
Assembling bees.
Each of 1 bees will fire 1 rounds, 1 at a time.
Stinging URL so it will be cached for the attack.
Organizing the swarm.
Bee 0 is joining the swarm.
Traceback (most recent call last):
  File "/usr/local/bin/bees", line 5, in <module>
    main.main()
  File "/Library/Python/2.7/site-packages/beeswithmachineguns/main.py", line 127, in main
    parse_options()
  File "/Library/Python/2.7/site-packages/beeswithmachineguns/main.py", line 119, in parse_options
    bees.attack(options.url, options.number, options.concurrent)
  File "/Library/Python/2.7/site-packages/beeswithmachineguns/bees.py", line 325, in attack
    results = pool.map(_attack, params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
paramiko.AuthenticationException: Authentication failed.

**Comment by nmallya** [comment]
This was caused by using the wrong user name for my ubuntu instance. Please ensure that you can ssh to the instance before running "bees attack..."

**Comment by temraz** [comment]
what is the command that you used please to fix the username issue ?
