### ISSUE TITLE
hurl option can't find url to hit

### ISSUE THREAD

**Issue by SafaTinaztepe** [newsapps/beeswithmachineguns#152]
Hello

When I run the CLI command for bees with:
  ~$bees attack -u $testurl

It works perfectly.  But when I download, make, build, and try to use hurl:
  ~$bees attack -j -u $testurl

I get back a zero division error:
  
> Please check the url entered, also possible no requests were successful Line: 1032
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "build/bdist.linux-x86_64/egg/beeswithmachineguns/bees.py", line 896, in hurl_attack
    summarized_results = _hurl_summarize_results(results, params, csv_filename)
  File "build/bdist.linux-x86_64/egg/beeswithmachineguns/bees.py", line 1174, in _hurl_summarize_results
    summarized_results['request_time_cdf'] = _get_request_time_cdf(summarized_results['total_complete_requests'], summarized_results['complete_bees'])
  File "build/bdist.linux-x86_64/egg/beeswithmachineguns/bees.py", line 545, in _get_request_time_cdf
    for r in complete_bees]
ZeroDivisionError: integer division or modulo by zero

 - I'm using 19 bees
 - python 2.7.6
 - Ubuntu 16.04
 - I used the same url with and without hurl
 - I ran hurl on the same url with its own CLI, and it worked perfectly

Is there an extra step to configure hurl to be accessible by bees that I missed, or does this look like a new issue?

**Comment by R4wm** [comment]
There is a list ami's that have hurl preinstalled. Could you try using one of these? https://github.com/newsapps/beeswithmachineguns/blob/master/regions.json

**Comment by merkelct** [comment]
Seeing the same as @SafaTinaztepe and the ami in the json does not seem to be available any other suggestions?

**Comment by R4wm** [comment]
You could install hurl on your own ami and use that I will check and
resolve the ami this week

**Comment by R4wm** [comment]
ill look into the ami today, thank you for the heads up. Can you specify
which AMI was not working ?

**Comment by merkelct** [comment]
@R4wm its the one in the regions file ami-ec737e86 for us-east-1 thanks for looking at it

**Comment by R4wm** [comment]
@merkelct you are correct, that AMI does not exist, here is the correct AMI for that region. I will update the json regions and submit a pull request today. 
Additionally, if you run into something like this , you can search the community AMI's with 'bee-image'
Thank you very much for bringing this to my attention, please let me know if you have any other problems regarding the AMI's or hurl integration. 

```$ bees up -s 2 -k bees -g default -l ubuntu -i ami-b94250d3 -z us-east-1b
New bees will use the "default" EC2 security group. Please note that port 22 (SSH) is not normally open on this group. You will need to use to the EC2 tools to open it before you will be able to attack.
Connecting to the hive.
GroupId found: default
Placement: us-east-1b
Attempting to call up 2 bees.
Waiting for bees to load their machine guns...
.
.
.
.
.
Bee i-98c01999 is ready for the attack.
Bee i-9bc0199a is ready for the attack.
The swarm has assembled 2 bees.
```

**Comment by R4wm** [comment]
@SafaTinaztepe im very sorry for the wait, ideally you can use hurl on an AMI with it preinstalled.. but yes if you have installed hurl on instance that you are running, then hurl should run fine. 
I did run your command from an AMI that has hurl pre-installed successfully. See output at bottom. 
My thoughts are, its possible you may have manually installed a newer version of hurl and "may" have ssomething to do with that. I spoke with the Author of hurl, its should be fine. What I will do is install latest version of hurl on an AWS instance to see if i can replicate the problem you are seeing

```bash
$ bees attack -j -u $testurl
us-east-1b
Read 2 bees from the roster: us-east-1b
Connecting to the hive.
Assembling bees.
Each of 2 bees will fire 500 rounds, 50 at a time.
Stinging URL so it will be cached for the attack.
Organizing the swarm.
Bee 0 is joining the swarm.
Bee 1 is joining the swarm.
Bee 0 is firing her machine gun. Bang bang!
Bee 1 is firing her machine gun. Bang bang!
Offensive complete.

Summarized Results
     Total bytes:		374345037
     Seconds:			60
     Connect-ms-max:		204.789000
     1st-resp-ms-max:		9106.659000
     1st-resp-ms-mean:		188.217812
     Fetches/sec mean:		259.358109
     connect-ms-min:		0.000000
     Total fetches:		31131
     bytes/sec mean:		3118737.628285
     end2end-ms-min mean:	81.954000
     mean-bytes-per-conn:	12024.743617
     connect-ms-mean:		1.586424

Response Codes:
     2xx:			31031
     3xx:			0
     4xx:			0
     5xx:			0

Mission Assessment: Target crushed bee offensive.
The swarm is awaiting new orders.


$ bees attack -j -u $testurl --long_output
us-east-1b
Read 2 bees from the roster: us-east-1b
Connecting to the hive.
Assembling bees.
Each of 2 bees will fire 500 rounds, 50 at a time.
Stinging URL so it will be cached for the attack.
Organizing the swarm.
Bee 0 is joining the swarm.
Bee 1 is joining the swarm.
Bee 0 is firing her machine gun. Bang bang!
Bee 1 is firing her machine gun. Bang bang!
hurl http://pacificbaptistchurch.com/ -p 50  -H "Content-Type : text/plain" -o /tmp/tmp.dhpB0UtMW5 -l 60 -t 1 -j

i-98c01999
ec2-107-22-103-131.compute-1.amazonaws.com
Running 1 threads 50 parallel connections per thread with 1 reqests per connection
+-----------/-----------+-----------+-----------+--------------+-----------+-------------+-----------+
|    Cmpltd /     Total |    IdlKil |    Errors | kBytes Recvd |   Elapsed |       Req/s |      MB/s |
+-----------/-----------+-----------+-----------+--------------+-----------+-------------+-----------+
|         0 /         0 |         0 |         0 |         0.00 |     0.50s |       0.00s |     0.00s |
|       103 /       103 |         0 |         0 |       627.76 |     1.00s |     206.00s |     1.23s |
|       170 /       170 |         0 |         0 |      1395.71 |     1.50s |     134.00s |     1.50s |
|       248 /       248 |         0 |         0 |      2314.24 |     2.00s |     156.00s |     1.79s |
|       332 /       332 |         0 |         0 |      3279.92 |     2.50s |     168.00s |     1.89s |
|       426 /       426 |         0 |         0 |      4384.53 |     3.00s |     188.00s |     2.16s |
|       538 /       538 |         0 |         0 |      5675.88 |     3.50s |     224.00s |     2.52s |
|       664 /       664 |         0 |         0 |      7149.86 |     4.00s |     252.00s |     2.88s |
|       823 /       823 |         0 |         0 |      9001.99 |     4.50s |     318.00s |     3.62s |
|       992 /       992 |         0 |         0 |     10956.30 |     5.00s |     337.33s |     3.81s |
|      1226 /      1226 |         0 |         0 |     13690.66 |     5.50s |     468.00s |     5.34s |
|      1472 /      1472 |         0 |         0 |     16540.54 |     6.00s |     492.00s |     5.57s |
|      1724 /      1724 |         0 |         0 |     19478.59 |     6.50s |     504.00s |     5.74s |
|      1967 /      1967 |         0 |         0 |     22306.30 |     7.00s |     486.00s |     5.52s |
|      2164 /      2164 |         0 |         0 |     24594.76 |     7.50s |     394.00s |     4.47s |
|      2349 /      2349 |         0 |         0 |     26747.88 |     8.00s |     370.00s |     4.21s |
|      2534 /      2534 |         0 |         0 |     28913.72 |     8.50s |     370.00s |     4.23s |
|      2700 /      2700 |         0 |         0 |     30823.20 |     9.00s |     331.34s |     3.72s |
|      2849 /      2849 |         0 |         0 |     32566.06 |     9.50s |     298.00s |     3.40s |
|      2985 /      2985 |         0 |         0 |     34136.17 |    10.00s |     272.00s |     3.07s |
|      3112 /      3112 |         0 |         0 |     35613.27 |    10.50s |     254.00s |     2.88s |
|      3246 /      3246 |         0 |         0 |     37181.70 |    11.00s |     268.00s |     3.06s |
|      3383 /      3383 |         0 |         0 |     38775.12 |    11.50s |     274.00s |     3.11s |
|      3514 /      3514 |         0 |         0 |     40300.17 |    12.00s |     262.00s |     2.98s |
|      3650 /      3650 |         0 |         0 |     41872.00 |    12.50s |     272.00s |     3.07s |
|      3784 /      3784 |         0 |         0 |     43440.43 |    13.00s |     268.00s |     3.06s |
|      3918 /      3918 |         0 |         0 |     44996.13 |    13.50s |     267.47s |     3.03s |
|      4052 /      4052 |         0 |         0 |     46550.41 |    14.00s |     268.00s |     3.04s |
|      4187 /      4187 |         0 |         0 |     48130.46 |    14.50s |     270.00s |     3.09s |
|      4318 /      4318 |         0 |         0 |     49639.83 |    15.00s |     262.00s |     2.95s |
|      4454 /      4454 |         0 |         0 |     51230.10 |    15.50s |     272.00s |     3.11s |
|      4590 /      4590 |         0 |         0 |     52803.39 |    16.00s |     272.00s |     3.07s |
|      4724 /      4724 |         0 |         0 |     54373.22 |    16.50s |     268.00s |     3.07s |
|      4856 /      4856 |         0 |         0 |     55908.40 |    17.00s |     264.00s |     3.00s |
|      4988 /      4988 |         0 |         0 |     57432.16 |    17.50s |     263.47s |     2.97s |
|      5121 /      5121 |         0 |         0 |     58979.06 |    18.00s |     266.00s |     3.02s |
|      5252 /      5252 |         0 |         0 |     60512.58 |    18.50s |     262.00s |     3.00s |
|      5386 /      5386 |         0 |         0 |     62066.86 |    19.00s |     268.00s |     3.04s |
|      5522 /      5522 |         0 |         0 |     63645.74 |    19.50s |     272.00s |     3.08s |
|      5652 /      5652 |         0 |         0 |     65157.62 |    20.00s |     260.00s |     2.95s |
|      5783 /      5783 |         0 |         0 |     66679.85 |    20.51s |     261.48s |     2.97s |
|      5918 /      5918 |         0 |         0 |     68255.65 |    21.01s |     270.00s |     3.08s |
|      6049 /      6049 |         0 |         0 |     69783.51 |    21.51s |     262.00s |     2.98s |
|      6183 /      6183 |         0 |         0 |     71330.71 |    22.01s |     268.00s |     3.02s |
|      6315 /      6315 |         0 |         0 |     72868.58 |    22.51s |     264.00s |     3.00s |
|      6445 /      6445 |         0 |         0 |     74386.11 |    23.01s |     260.00s |     2.96s |
|      6586 /      6586 |         0 |         0 |     76017.56 |    23.51s |     282.00s |     3.19s |
|      6724 /      6724 |         0 |         0 |     77622.60 |    24.01s |     276.00s |     3.13s |
|      6861 /      6861 |         0 |         0 |     79216.00 |    24.51s |     274.00s |     3.11s |
|      6997 /      6997 |         0 |         0 |     80798.96 |    25.01s |     271.46s |     3.09s |
|      7128 /      7128 |         0 |         0 |     82321.12 |    25.51s |     262.00s |     2.97s |
|      7262 /      7262 |         0 |         0 |     83885.31 |    26.01s |     268.00s |     3.06s |
|      7401 /      7401 |         0 |         0 |     85497.75 |    26.51s |     278.00s |     3.15s |
|      7540 /      7540 |         0 |         0 |     87113.00 |    27.01s |     278.00s |     3.15s |
|      7681 /      7681 |         0 |         0 |     88764.25 |    27.51s |     282.00s |     3.23s |
|      7815 /      7815 |         0 |         0 |     90311.22 |    28.01s |     268.00s |     3.02s |
|      7948 /      7948 |         0 |         0 |     91870.84 |    28.51s |     266.00s |     3.05s |
|      8084 /      8084 |         0 |         0 |     93441.31 |    29.01s |     271.46s |     3.06s |
|      8218 /      8218 |         0 |         0 |     94998.42 |    29.51s |     268.00s |     3.04s |
|      8353 /      8353 |         0 |         0 |     96568.43 |    30.01s |     270.00s |     3.07s |
|      8484 /      8484 |         0 |         0 |     98103.32 |    30.51s |     262.00s |     3.00s |
|      8620 /      8620 |         0 |         0 |     99673.80 |    31.01s |     272.00s |     3.07s |
|      8757 /      8757 |         0 |         0 |    101267.22 |    31.51s |     274.00s |     3.11s |
|      8892 /      8892 |         0 |         0 |    102837.38 |    32.01s |     270.00s |     3.07s |
|      9025 /      9025 |         0 |         0 |    104385.62 |    32.51s |     266.00s |     3.02s |
|      9159 /      9159 |         0 |         0 |    105954.02 |    33.01s |     268.00s |     3.06s |
|      9295 /      9295 |         0 |         0 |    107524.50 |    33.51s |     271.46s |     3.06s |
|      9430 /      9430 |         0 |         0 |    109096.07 |    34.01s |     270.00s |     3.07s |
|      9564 /      9564 |         0 |         0 |    110675.80 |    34.51s |     268.00s |     3.09s |
|      9702 /      9702 |         0 |         0 |    112258.08 |    35.01s |     276.00s |     3.09s |
|      9833 /      9833 |         0 |         0 |    113785.93 |    35.51s |     262.00s |     2.98s |
|      9967 /      9967 |         0 |         0 |    115344.45 |    36.01s |     268.00s |     3.04s |
|     10102 /     10102 |         0 |         0 |    116910.36 |    36.51s |     270.00s |     3.06s |
|     10238 /     10238 |         0 |         0 |    118499.13 |    37.01s |     272.00s |     3.10s |
|     10371 /     10371 |         0 |         0 |    120050.13 |    37.51s |     265.47s |     3.02s |
|     10506 /     10506 |         0 |         0 |    121608.92 |    38.01s |     270.00s |     3.04s |
|     10639 /     10639 |         0 |         0 |    123160.06 |    38.51s |     266.00s |     3.03s |
|     10775 /     10775 |         0 |         0 |    124737.60 |    39.01s |     272.00s |     3.08s |
|     10909 /     10909 |         0 |         0 |    126296.07 |    39.51s |     268.00s |     3.04s |
|     11045 /     11045 |         0 |         0 |    127883.46 |    40.01s |     272.00s |     3.10s |
|     11177 /     11177 |         0 |         0 |    129412.89 |    40.51s |     264.00s |     2.99s |
|     11310 /     11310 |         0 |         0 |    130959.65 |    41.01s |     265.47s |     3.01s |
|     11448 /     11448 |         0 |         0 |    132564.71 |    41.51s |     276.00s |     3.13s |
|     11586 /     11586 |         0 |         0 |    134176.82 |    42.01s |     276.00s |     3.15s |
|     11723 /     11723 |         0 |         0 |    135763.13 |    42.51s |     274.00s |     3.10s |
|     11856 /     11856 |         0 |         0 |    137321.24 |    43.01s |     266.00s |     3.04s |
|     11988 /     11988 |         0 |         0 |    138856.47 |    43.51s |     264.00s |     3.00s |
|     12124 /     12124 |         0 |         0 |    140426.94 |    44.01s |     272.00s |     3.07s |
|     12256 /     12256 |         0 |         0 |    142003.20 |    44.51s |     264.00s |     3.08s |
|     12399 /     12399 |         0 |         0 |    143628.07 |    45.01s |     286.00s |     3.17s |
|     12532 /     12532 |         0 |         0 |    145177.76 |    45.51s |     265.47s |     3.02s |
|     12664 /     12664 |         0 |         0 |    146707.24 |    46.01s |     264.00s |     2.99s |
|     12796 /     12796 |         0 |         0 |    148243.91 |    46.51s |     264.00s |     3.00s |
|     12929 /     12929 |         0 |         0 |    149800.70 |    47.01s |     266.00s |     3.04s |
|     13064 /     13064 |         0 |         0 |    151359.53 |    47.51s |     270.00s |     3.04s |
|     13198 /     13198 |         0 |         0 |    152917.84 |    48.01s |     268.00s |     3.04s |
|     13325 /     13325 |         0 |         0 |    154421.76 |    48.51s |     254.00s |     2.94s |
|     13461 /     13461 |         0 |         0 |    155983.75 |    49.01s |     272.00s |     3.05s |
|     13592 /     13592 |         0 |         0 |    157566.78 |    49.51s |     261.48s |     3.09s |
|     13727 /     13727 |         0 |         0 |    159132.66 |    50.01s |     270.00s |     3.06s |
|     13863 /     13863 |         0 |         0 |    160676.21 |    50.51s |     272.00s |     3.01s |
|     13995 /     13995 |         0 |         0 |    162198.75 |    51.01s |     264.00s |     2.97s |
|     14126 /     14126 |         0 |         0 |    163740.77 |    51.51s |     262.00s |     3.01s |
|     14264 /     14264 |         0 |         0 |    165327.44 |    52.01s |     276.00s |     3.10s |
|     14397 /     14397 |         0 |         0 |    166888.47 |    52.51s |     266.00s |     3.05s |
|     14534 /     14534 |         0 |         0 |    168456.33 |    53.01s |     274.00s |     3.06s |
|     14664 /     14664 |         0 |         0 |    169968.31 |    53.51s |     259.48s |     2.95s |
|     14801 /     14801 |         0 |         0 |    171573.04 |    54.01s |     274.00s |     3.13s |
|     14934 /     14934 |         0 |         0 |    173117.10 |    54.51s |     266.00s |     3.02s |
|     15072 /     15072 |         0 |         0 |    174716.41 |    55.01s |     276.00s |     3.12s |
|     15205 /     15205 |         0 |         0 |    176260.38 |    55.51s |     266.00s |     3.02s |
|     15336 /     15336 |         0 |         0 |    177813.64 |    56.01s |     262.00s |     3.03s |
|     15469 /     15469 |         0 |         0 |    179374.67 |    56.51s |     266.00s |     3.05s |
|     15608 /     15608 |         0 |         0 |    180967.31 |    57.01s |     278.00s |     3.11s |
|     15744 /     15744 |         0 |         0 |    182544.73 |    57.51s |     272.00s |     3.08s |
|     15882 /     15882 |         0 |         0 |    184141.23 |    58.02s |     275.45s |     3.11s |
|     16011 /     16011 |         0 |         0 |    185685.36 |    58.52s |     258.00s |     3.02s |
|     16151 /     16151 |         0 |         0 |    187268.36 |    59.02s |     280.00s |     3.09s |
|     16288 /     16288 |         0 |         0 |    188884.40 |    59.52s |     274.00s |     3.16s |
|     16427 /     16427 |         0 |         0 |    190489.73 |    60.02s |     278.00s |     3.14s |

Bee: i-98c01999
max-parallel:		50
1st-resp-ms-min:	74.106
response-codes
	200:		16377
seconds:		60.015
connect-ms-max:		195.905
1st-resp-ms-max:	6007.013
bytes:			197558387.0
1st-resp-ms-mean:	176.015078464
end2end-ms-mean:	181.382820053
fetches-per-sec:	273.714904607
connect-ms-min:		0.0
fetches:		16427
bytes-per-sec:		3291816.82913
end2end-ms-min:		76.13
end2end-ms-max:		6008.649
mean-bytes-per-conn:	12026.4434772
connect-ms-mean:	1.69237216828
```

**Comment by R4wm** [comment]
@SafaTinaztepe @merkelct  so i found the root cause of  the issue you were seeing when manually installing hurl and getting the error, That version of hurl was crashing when command was passed  in from  bees. so bees script was still trying to parse information that was not there. 
Good news. our Dev for hurl released fix for this. I took the liberty of creating a new AMI list , tested and made pull request. You can also manually install hurl if you like. 
I am working on adding verbose output for debugging in future and will also put the parser in a try catch. Thanks for your help with this : )

**Comment by R4wm** [comment]
new AMI's tested
```bash

:~/git/beeswithmachineguns$
:~/git/beeswithmachineguns$ ./bees up -l ubuntu -g bees2 -k bees_key -s 2 -z ap-northeast-1a,eu-west-1b,us-east-1b,us-west-1b,us-west-2b,ap-southeast-1a,ap-southeast-2b,sa-east-1b -i ami-eeeb258f,ami-b31362c0,ami-1b55360c,ami-8b014ceb,ami-d5be69b5,ami-b0fa22d3,ami-739cab10,ami-4cb92820
Connecting to the hive.
GroupId found: bees2
Placement: ap-northeast-1a
Attempting to call up 2 bees.
Connecting to the hive.
GroupId found: bees2
Placement: eu-west-1b
Attempting to call up 2 bees.
Connecting to the hive.
GroupId found: bees2
Placement: us-east-1b
Attempting to call up 2 bees.
Connecting to the hive.
GroupId found: bees2
Placement: us-west-1b
Attempting to call up 2 bees.
Connecting to the hive.
GroupId found: bees2
Placement: us-west-2b
Attempting to call up 2 bees.
Connecting to the hive.
GroupId found: bees2
Placement: ap-southeast-1a
Attempting to call up 2 bees.
Connecting to the hive.
GroupId found: bees2
Placement: ap-southeast-2b
Attempting to call up 2 bees.
Waiting for bees to load their machine guns...
Waiting for bees to load their machine guns...
Connecting to the hive.
GroupId found: bees2
Placement: sa-east-1b
Attempting to call up 2 bees.
Waiting for bees to load their machine guns...
.
Waiting for bees to load their machine guns...
Waiting for bees to load their machine guns...
.
.
.
.
Waiting for bees to load their machine guns...
Waiting for bees to load their machine guns...
.
.
Waiting for bees to load their machine guns...
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
.
Bee i-afd4a900 is ready for the attack.
.
.
.
Bee i-ab3f211e is ready for the attack.
.
.
.
Bee i-cbabb5c5 is ready for the attack.
Bee i-c8abb5c6 is ready for the attack.
Bee i-0e080882 is ready for the attack.
The swarm has assembled 2 bees.
.
.
Bee i-a0d4a90f is ready for the attack.
The swarm has assembled 2 bees.
Bee i-34514320 is ready for the attack.
.
.
Bee i-5dd954c9 is ready for the attack.
Bee i-5ed954ca is ready for the attack.
The swarm has assembled 2 bees.
Bee i-45e2d9da is ready for the attack.
Bee i-44e2d9db is ready for the attack.
The swarm has assembled 2 bees.
Bee i-0f080883 is ready for the attack.
The swarm has assembled 2 bees.
Bee i-dbe20f7c is ready for the attack.
Bee i-dae20f7d is ready for the attack.
The swarm has assembled 2 bees.
Bee i-35514321 is ready for the attack.
The swarm has assembled 2 bees.
Bee i-aa3f211f is ready for the attack.
The swarm has assembled 2 bees.
:~/git/beeswithmachineguns$
:~/git/beeswithmachineguns$
:~/git/beeswithmachineguns$ ./bees report
Read 2 bees from the roster: eu-west-1b
Bee i-0e080882: running @ 54.154.141.31
Bee i-0f080883: running @ 54.154.181.56
Read 2 bees from the roster: ap-northeast-1a
Bee i-45e2d9da: running @ 54.199.156.204
Bee i-44e2d9db: running @ 54.199.146.77
Read 2 bees from the roster: ap-southeast-1a
Bee i-dbe20f7c: running @ 52.77.219.158
Bee i-dae20f7d: running @ 54.169.149.81
Read 2 bees from the roster: us-west-1b
Bee i-ab3f211e: running @ 52.53.157.188
Bee i-aa3f211f: running @ 54.153.67.82
Read 2 bees from the roster: us-east-1b
Bee i-cbabb5c5: running @ 54.161.43.90
Bee i-c8abb5c6: running @ 54.89.147.55
Read 2 bees from the roster: ap-southeast-2b
Bee i-afd4a900: running @ 54.206.121.44
Bee i-a0d4a90f: running @ 54.206.118.134
Read 2 bees from the roster: us-west-2b
Bee i-5dd954c9: running @ 54.149.165.50
Bee i-5ed954ca: running @ 54.201.195.4
Read 2 bees from the roster: sa-east-1b
Bee i-34514320: running @ 52.67.33.123
Bee i-35514321: running @ 52.67.49.74
:~/git/beeswithmachineguns$
:~/git/beeswithmachineguns$
:~/git/beeswithmachineguns$
:~/git/beeswithmachineguns$
:~/git/beeswithmachineguns$
:~/git/beeswithmachineguns$ #allowing bees to initalize
:~/git/beeswithmachineguns$
:~/git/beeswithmachineguns$
:~/git/beeswithmachineguns$ ./bees attack -j -u $testurl -f200 -H "Accept : text/html"
eu-west-1b
Read 2 bees from the roster: eu-west-1b
Connecting to the hive.
Assembling bees.
ap-northeast-1a
Read 2 bees from the roster: ap-northeast-1a
Connecting to the hive.
Assembling bees.
ap-southeast-1a
Read 2 bees from the roster: ap-southeast-1a
Connecting to the hive.
Assembling bees.
us-west-1b
Read 2 bees from the roster: us-west-1b
Connecting to the hive.
Assembling bees.
us-east-1b
Read 2 bees from the roster: us-east-1b
Connecting to the hive.
Assembling bees.
Each of 2 bees will fire 500 rounds, 50 at a time.
Stinging URL so it will be cached for the attack.
Organizing the swarm.
Bee 0 is joining the swarm.
Bee 1 is joining the swarm.
Each of 2 bees will fire 500 rounds, 50 at a time.
Stinging URL so it will be cached for the attack.
Each of 2 bees will fire 500 rounds, 50 at a time.
Stinging URL so it will be cached for the attack.
Organizing the swarm.
Bee 0 is joining the swarm.
Bee 1 is joining the swarm.
ap-southeast-2b
Read 2 bees from the roster: ap-southeast-2b
Connecting to the hive.
Assembling bees.
Organizing the swarm.
Bee 0 is joining the swarm.
Bee 1 is joining the swarm.
us-west-2b
Read 2 bees from the roster: us-west-2b
Connecting to the hive.
Assembling bees.
Bee 0 is firing her machine gun. Bang bang!
Each of 2 bees will fire 500 rounds, 50 at a time.
Stinging URL so it will be cached for the attack.
Organizing the swarm.
Bee 0 is joining the swarm.
Bee 1 is joining the swarm.
sa-east-1b
Read 2 bees from the roster: sa-east-1b
Connecting to the hive.
Assembling bees.
Each of 2 bees will fire 500 rounds, 50 at a time.
Stinging URL so it will be cached for the attack.
Organizing the swarm.
Bee 0 is joining the swarm.
Bee 1 is joining the swarm.
Each of 2 bees will fire 500 rounds, 50 at a time.
Stinging URL so it will be cached for the attack.
Organizing the swarm.
Bee 0 is joining the swarm.
Bee 1 is joining the swarm.
Bee 1 is firing her machine gun. Bang bang!
Each of 2 bees will fire 500 rounds, 50 at a time.
Stinging URL so it will be cached for the attack.
Organizing the swarm.
Bee 0 is joining the swarm.
Bee 1 is joining the swarm.
Bee 1 is firing her machine gun. Bang bang!
Bee 1 is firing her machine gun. Bang bang!
Bee 0 is firing her machine gun. Bang bang!
Bee 1 is firing her machine gun. Bang bang!
Bee 0 is firing her machine gun. Bang bang!
Bee 0 is firing her machine gun. Bang bang!
Each of 2 bees will fire 500 rounds, 50 at a time.
Stinging URL so it will be cached for the attack.
Organizing the swarm.
Bee 0 is joining the swarm.
Bee 1 is joining the swarm.
Bee 1 is firing her machine gun. Bang bang!
Bee 0 is firing her machine gun. Bang bang!
Bee 1 is firing her machine gun. Bang bang!
Bee 0 is firing her machine gun. Bang bang!
Bee 1 is firing her machine gun. Bang bang!
Bee 0 is firing her machine gun. Bang bang!
Bee 1 is firing her machine gun. Bang bang!
Bee 0 is firing her machine gun. Bang bang!
Offensive complete.

Summarized Results
     Total bytes:               212000
     Seconds:                   0
     Connect-ms-max:            4.650000
     1st-resp-ms-max:           159.530000
     1st-resp-ms-mean:          60.534340
     Fetches/sec mean:          399.600798
     connect-ms-min:            0.000000
     Total fetches:             400
     bytes/sec mean:            211788.423154
     end2end-ms-min mean:       19.795500
     mean-bytes-per-conn:       530.000000
     connect-ms-mean:           0.700830

Response Codes:
     2xx:                       400
     3xx:                       0
     4xx:                       0
     5xx:                       0

Mission Assessment: Target crushed bee offensive.
The swarm is awaiting new orders.
Offensive complete.

Summarized Results
     Total bytes:               212000
     Seconds:                   1
     Connect-ms-max:            129.993000
     1st-resp-ms-max:           402.685000
     1st-resp-ms-mean:          175.173178
     Fetches/sec mean:          133.333333
     connect-ms-min:            0.000000
     Total fetches:             400
     bytes/sec mean:            70666.666667
     end2end-ms-min mean:       122.543500
     mean-bytes-per-conn:       530.000000
     connect-ms-mean:           27.074445

Response Codes:
     2xx:                       400
     3xx:                       0
     4xx:                       0
     5xx:                       0

Mission Assessment: Target crushed bee offensive.
The swarm is awaiting new orders.
Offensive complete.

Summarized Results
     Total bytes:               212000
     Seconds:                   1
     Connect-ms-max:            32.596000
     1st-resp-ms-max:           265.741000
     1st-resp-ms-mean:          107.425403
     Fetches/sec mean:          199.800200
     connect-ms-min:            0.000000
     Total fetches:             400
     bytes/sec mean:            105894.105894
     end2end-ms-min mean:       55.192500
     mean-bytes-per-conn:       530.000000
     connect-ms-mean:           4.779275

Response Codes:
     2xx:                       400
     3xx:                       0
     4xx:                       0
     5xx:                       0

Mission Assessment: Target crushed bee offensive.
The swarm is awaiting new orders.
Offensive complete.

Summarized Results
     Total bytes:               212000
     Seconds:                   1
     Connect-ms-max:            192.349000
     1st-resp-ms-max:           541.656000
     1st-resp-ms-mean:          264.911630
     Fetches/sec mean:          133.288918
     connect-ms-min:            0.000000
     Total fetches:             400
     bytes/sec mean:            70643.126804
     end2end-ms-min mean:       189.245000
     mean-bytes-per-conn:       530.000000
     connect-ms-mean:           44.586382

Response Codes:
     2xx:                       400
     3xx:                       0
     4xx:                       0
     5xx:                       0

Mission Assessment: Target crushed bee offensive.
The swarm is awaiting new orders.
Offensive complete.

Summarized Results
     Total bytes:               212000
     Seconds:                   1
     Connect-ms-max:            11.876000
     1st-resp-ms-max:           424.426000
     1st-resp-ms-mean:          254.749205
     Fetches/sec mean:          133.288918
     connect-ms-min:            0.000000
     Total fetches:             400
     bytes/sec mean:            70643.126804
     end2end-ms-min mean:       172.011500
     mean-bytes-per-conn:       530.000000
     connect-ms-mean:           2.832890

Response Codes:
     2xx:                       400
     3xx:                       0
     4xx:                       0
     5xx:                       0

Mission Assessment: Target crushed bee offensive.
The swarm is awaiting new orders.
Offensive complete.

Summarized Results
     Total bytes:               212000
     Seconds:                   1
     Connect-ms-max:            179.685000
     1st-resp-ms-max:           466.853000
     1st-resp-ms-mean:          257.788017
     Fetches/sec mean:          133.244504
     connect-ms-min:            0.000000
     Total fetches:             400
     bytes/sec mean:            70619.586942
     end2end-ms-min mean:       183.417500
     mean-bytes-per-conn:       530.000000
     connect-ms-mean:           43.701755

Response Codes:
     2xx:                       400
     3xx:                       0
     4xx:                       0
     5xx:                       0

Mission Assessment: Target crushed bee offensive.
The swarm is awaiting new orders.
Offensive complete.

Summarized Results
     Total bytes:               212000
     Seconds:                   2
     Connect-ms-max:            114.372000
     1st-resp-ms-max:           494.026000
     1st-resp-ms-mean:          260.096383
     Fetches/sec mean:          99.950025
     connect-ms-min:            0.000000
     Total fetches:             400
     bytes/sec mean:            52973.513243
     end2end-ms-min mean:       179.185000
     mean-bytes-per-conn:       530.000000
     connect-ms-mean:           28.387923

Response Codes:
     2xx:                       400
     3xx:                       0
     4xx:                       0
     5xx:                       0

Mission Assessment: Target crushed bee offensive.
The swarm is awaiting new orders.

Offensive complete.

Summarized Results
     Total bytes:               212000
     Seconds:                   2
     Connect-ms-max:            4.084000
     1st-resp-ms-max:           889.773000
     1st-resp-ms-mean:          236.832455
     Fetches/sec mean:          116.597264
     connect-ms-min:            0.000000
     Total fetches:             400
     bytes/sec mean:            61796.550093
     end2end-ms-min mean:       88.403000
     mean-bytes-per-conn:       530.000000
     connect-ms-mean:           0.665180

Response Codes:
     2xx:                       400
     3xx:                       0
     4xx:                       0
     5xx:                       0

Mission Assessment: Target crushed bee offensive.
The swarm is awaiting new orders.
:~/git/beeswithmachineguns$
:~/git/beeswithmachineguns$
:~/git/beeswithmachineguns$
:~/git/beeswithmachineguns$
:~/git/beeswithmachineguns$
:~/git/beeswithmachineguns$
:~/git/beeswithmachineguns$ ./bees down
Read 2 bees from the roster: eu-west-1b
Connecting to the hive.
Calling off the swarm for eu-west-1b.
Stood down 2 bees.
Read 2 bees from the roster: ap-northeast-1a
Connecting to the hive.
Calling off the swarm for ap-northeast-1a.
Stood down 2 bees.
Read 2 bees from the roster: ap-southeast-1a
Connecting to the hive.
Calling off the swarm for ap-southeast-1a.
Stood down 2 bees.
Read 2 bees from the roster: us-west-1b
Connecting to the hive.
Calling off the swarm for us-west-1b.
Stood down 2 bees.
Read 2 bees from the roster: us-east-1b
Connecting to the hive.
Calling off the swarm for us-east-1b.
Stood down 2 bees.
Read 2 bees from the roster: ap-southeast-2b
Connecting to the hive.
Calling off the swarm for ap-southeast-2b.
Stood down 2 bees.
Read 2 bees from the roster: us-west-2b
Connecting to the hive.
Calling off the swarm for us-west-2b.
Stood down 2 bees.
Read 2 bees from the roster: sa-east-1b
Connecting to the hive.
Calling off the swarm for sa-east-1b.
Stood down 2 bees.
:~/git/beeswithmachineguns$
```

**Comment by SafaTinaztepe** [comment]
Looks great, guys!

Thanks for all your work!

**Comment by YashishDua** [comment]
I am getting the same error for us-east-1. Tried using all AMIs specified in this thread.
