### ISSUE TITLE
conflicting option string(s)

### ISSUE THREAD

**Issue by hammygoonan** [newsapps/beeswithmachineguns#154]
Many thanks for this amazing tool!

I'm getting the following error when trying to run any commands:

```
Traceback (most recent call last):
  File "./bees", line 6, in <module>
    main.main()
  File "/path/to/beeswithmachineguns/beeswithmachineguns/main.py", line 266, in main
    parse_options()
  File "/path/to/beeswithmachineguns/beeswithmachineguns/main.py", line 127, in parse_options
    help="The flag to sting (ping to cache) url before attack (default: 1). 0: no sting, 1: sting sequentially, 2: sting in parallel")
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/optparse.py", line 1021, in add_option
    self._check_conflict(option)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/optparse.py", line 996, in _check_conflict
    option)
optparse.OptionConflictError: option -s/--sting: conflicting option string(s): -s
```

The above is in OS X El Capitan and I get more or less the same error when I try it on an Ubuntu virtual machine as well.

**Comment by SafaTinaztepe** [comment]
I just submitted a pull request to change the sting flag from -s, which conflicted with --servers, to -I <capital i> which isn't occupied by any other flags.

Bees will work again when the request is approved.
