### ISSUE TITLE
Invalid availability zone

### ISSUE THREAD

**Issue by danninux** [newsapps/beeswithmachineguns#163]
Hi All,
That still didnt fix for me. I tried

[Boto]
ec2_region_name = ap-southeast-1
ec2_region_endpoint = ec2.ap-southeast-1.amazonaws.com

bees up -s 2 -k testing -z ap-southeast-1

Traceback (most recent call last):
File "/usr/local/bin/bees", line 5, in
main.main()
File "/usr/local/lib/python2.7/site-packages/beeswithmachineguns/main.py", line 127, in main
parse_options()
File "/usr/local/lib/python2.7/site-packages/beeswithmachineguns/main.py", line 111, in parse_options
bees.up(options.servers, options.group, options.zone, options.instance, options.login, options.key)
File "/usr/local/lib/python2.7/site-packages/beeswithmachineguns/bees.py", line 104, in up
placement=zone)
File "/usr/local/lib/python2.7/site-packages/boto/ec2/connection.py", line 618, in run_instances
return self.get_object('RunInstances', params, Reservation, verb='POST')
File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 699, in get_object
raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
InvalidParameterValueInvalid availability zone: [ap-southeast-1]b8641ad4-6200-41dc-8d56-21e17e61e5c4

Pls, anyone help this ?
Thanks.

**Comment by mfrederickson** [comment]
See my response to your other comment, but I think you also may need to specify an instance identifier to start up... one that has the software preinstalled on it for being a "bee".  You can find those in the regions json file in the root of the project.   For example, I kicked off my bees with this command:
```
bees up -s 2 -g public -k iamuseraccnt -z us-west-2a -i ami-e8c93e88 -l ubuntu
```
The value for the `-i` came from that regions file, and the `-l ubuntu` was used because that was the default user for the image I chose.

**Comment by danninux** [comment]
@mfrederickson , still error.

$ bees up -s 2 -g public -k test -z ap-southeast-1a -i ami-7243e611 -l ec2-user
Connecting to the hive.
Attempting to call up 2 bees.
Traceback (most recent call last):
  File "/usr/local/bin/bees", line 5, in <module>
    main.main()
  File "/usr/local/lib/python2.7/site-packages/beeswithmachineguns/main.py", line 127, in main
    parse_options()
  File "/usr/local/lib/python2.7/site-packages/beeswithmachineguns/main.py", line 111, in parse_options
    bees.up(options.servers, options.group, options.zone, options.instance, options.login, options.key)
  File "/usr/local/lib/python2.7/site-packages/beeswithmachineguns/bees.py", line 104, in up
    placement=zone)
  File "/usr/local/lib/python2.7/site-packages/boto/ec2/connection.py", line 618, in run_instances
    return self.get_object('RunInstances', params, Reservation, verb='POST')
  File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 699, in get_object
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterValue</Code><Message>Invalid availability zone: [ap-southeast-1a]</Message></Error></Errors><RequestID>9e4e984e-8f58-4423-b045-93c4eaadbfe3</RequestID></Response>

Wired, what's wrong...?

**Comment by mfrederickson** [comment]
@danninux where did you get that instance id?  I thought you'd have to use one from the regions.json file like this one that is in that zone you specified:  https://github.com/newsapps/beeswithmachineguns/blob/master/regions.json#L10

**Comment by mfrederickson** [comment]
@danninux you should also peek at #158 based on their output that person was able to connect to your region.

**Comment by danninux** [comment]
@mfrederickson oh ic...but still error

$ bees up -s 2 -g public -k test -z ap-southeast-1a -i ami-fd489d9e -l ec2-user
Connecting to the hive.
Attempting to call up 2 bees.
Traceback (most recent call last):
  File "/usr/local/bin/bees", line 5, in <module>
    main.main()
  File "/usr/local/lib/python2.7/site-packages/beeswithmachineguns/main.py", line 127, in main
    parse_options()
  File "/usr/local/lib/python2.7/site-packages/beeswithmachineguns/main.py", line 111, in parse_options
    bees.up(options.servers, options.group, options.zone, options.instance, options.login, options.key)
  File "/usr/local/lib/python2.7/site-packages/beeswithmachineguns/bees.py", line 104, in up
    placement=zone)
  File "/usr/local/lib/python2.7/site-packages/boto/ec2/connection.py", line 618, in run_instances
    return self.get_object('RunInstances', params, Reservation, verb='POST')
  File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 699, in get_object
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterValue</Code><Message>Invalid availability zone: [ap-southeast-1a]</Message></Error></Errors><RequestID>66c81939-d968-4d6a-bd9f-adf4abf2185a</RequestID></Response>
 
Very wired, if I dont use -z ap-southeast-1a, bees can running but use default zone us-east-1.
But I want zone go to -z ap-southeast-1a.

**Comment by mfrederickson** [comment]
I wonder what your zone is in your .boto file, and if your AWS account is set up to use that zone, or if that even matters?  I am not that experienced with AWS.

**Comment by danninux** [comment]
This my .boto file :
[Credentials]
aws_access_key_id = xxx
aws_secret_access_key = xxx

[Boto]
ec2_region_name = ap-southeast-1
ec2_region_endpoint = ec2.ap-southeast-1.amazonaws.com

Anything wrong with this?

**Comment by danninux** [comment]
Done, thanks @mfrederickson
