### ISSUE TITLE
When using bees command getting following error

### ISSUE THREAD

**Issue by srinvasarao** [newsapps/beeswithmachineguns#181]
Each of 1 bees will fire 100 rounds, 100 at a time.
Stinging URL so it will be cached for the attack.
Organizing the swarm.
Bee 0 is joining the swarm.
Bee 0 is firing her machine gun. Bang bang!
Please check the url entered, also possible no requests were successful Line: 1032
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 757, in run
    self.__target(*self.__args, **self.__kwargs)
  File "build/bdist.linux-x86_64/egg/beeswithmachineguns/bees.py", line 932, in hurl_attack
    summarized_results = _hurl_summarize_results(results, params, csv_filename)
  File "build/bdist.linux-x86_64/egg/beeswithmachineguns/bees.py", line 1210, in _hurl_summarize_results
    summarized_results['request_time_cdf'] = _get_request_time_cdf(summarized_results['total_complete_requests'], summarized_results['complete_bees'])
  File "build/bdist.linux-x86_64/egg/beeswithmachineguns/bees.py", line 611, in _get_request_time_cdf
    for r in complete_bees]
ZeroDivisionError: division by zero

**Comment by andrewmclagan** [comment]
Also receiving this error with:

ZeroDivisionError: division by zero

```
bees attack --hurl -u "https://api.exampleurl.com.au/search/jobs?locations=1&limit=100" \
    --number 40 \
    --concurrent 10 \
    --seconds 60 \
    --rate 1000 \
    --headers "Accept : application/json"
```

**Comment by jignesh248** [comment]
Not sure I am facing similar issues, Is it a possibility that it has something do with https
