### ISSUE TITLE
Accidentally deleted bees instances from AWS, how to reset beeswithmachineguns?

### ISSUE THREAD

**Issue by monkychia** [newsapps/beeswithmachineguns#182]
Our AWS admin was doing some clean-ups and accidentally deleted the bees instances from AWS.  Now every time we do bees up, it still recognizes the old bees instances.  But when doing a bees report, it fails to find the instance IDs.  What can we do to reset beeswithmachineguns so that it can start fresh again?  

bees up -s 2 -g test -k xxxx
Read 2 bees from the roster.
Bees are already assembled and awaiting orders.

bees report
Read 2 bees from the roster.
Traceback (most recent call last):
  File "/usr/local/bin/bees", line 5, in <module>
    main.main()
  File "/Library/Python/2.7/site-packages/beeswithmachineguns/main.py", line 127, in main
    parse_options()
  File "/Library/Python/2.7/site-packages/beeswithmachineguns/main.py", line 123, in parse_options
    bees.report()
  File "/Library/Python/2.7/site-packages/beeswithmachineguns/bees.py", line 138, in report
    reservations = ec2_connection.get_all_instances(instance_ids=instance_ids)
  File "/Library/Python/2.7/site-packages/boto/ec2/connection.py", line 456, in get_all_instances
    [('item', Reservation)], verb='POST')
  File "/Library/Python/2.7/site-packages/boto/connection.py", line 680, in get_list
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidInstanceID.NotFound</Code><Message>The instance IDs 'i-96959e81, i-97959e80' do not exist</Message></Error></Errors><RequestID>6bd64229-d8f6-4f6e-a437-60665be9f053</RequestID></Response>

**Comment by FliesLikeABrick** [comment]
@monkychia delete the .bees.[region name] file in the home directory of the user running BWMG

**Comment by FliesLikeABrick** [comment]
@cosmin  recommending merge of #196  and closing of this issue
