### ISSUE TITLE
Not all available AWS regions work

### ISSUE THREAD

**Issue by paulmarsicovetere** [newsapps/beeswithmachineguns#187]
I can configure bees up in the following regions:

us-east-1
us-west-1
us-west-2
eu-west-1
ap-southeast-2
ap-southeast-1
ap-northeast-1
sa-east-1

But for the following regions:
us-east-2
ca-central-1
eu-central-1
eu-west-2
ap-northeast-2
ap-south-1

I get this error each time:
`Connecting to the hive.
Traceback (most recent call last):
  File "/usr/local/bin/bees", line 6, in <module>
    main.main()
  File "/usr/local/lib/python2.7/site-packages/beeswithmachineguns/main.py", line 270, in main
    parse_options()
  File "/usr/local/lib/python2.7/site-packages/beeswithmachineguns/main.py", line 210, in parse_options
    bees.up(options.servers, options.group, options.zone, options.instance, options.type, options.login, options.key, options.subnet, options.bid)
  File "/usr/local/lib/python2.7/site-packages/beeswithmachineguns/bees.py", line 176, in up
    raise Exception("Invalid zone specified? Unable to connect to region using zone name")
Exception: Invalid zone specified? Unable to connect to region using zone name`

Any ideas?

**Comment by cosmin** [comment]
The version of boto probably needs to be updated in order to be aware of the latest region names. How did you install bees? Did you pull it from master or did you install it through pip?

**Comment by paulmarsicovetere** [comment]
I just ran `pip install https://github.com/newsapps/beeswithmachineguns/archive/master.zip`, so I will try updating the boto version and try again.

**Comment by FliesLikeABrick** [comment]
@paulmarsicovetere  any update?

**Comment by z0ph** [comment]
Hi,

Same here, `eu-west-3` doesn't work. Fresh install.

**Comment by 0x2615** [comment]
I too encountered this issue. Running this: `pip install --upgrade boto` updated `boto` and solved the issue for me.
