### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by bcbeatty** [newsapps/beeswithmachineguns#211]
I'm trying the Installation for developers (w/ virtualenv + virtualenvwrapper).
A few issues:
add a line for "pip install virtualenv"

mkvirtualenv --no-site-packages beesenv 
should be
virtualenv --no-site-packages beesenv

When I attempt 
 pip install -r requirements.txt
I get the following error
 
    cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -Isrc/ -Isrc/inc-msvc/ -Ic:\users\beabri01\appdata\local\programs\python\python36\include -Ic:\users\beabri01\appdata\local\programs\python\python36\include "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" /Tcsrc/winrand.c /Fobuild\temp.win-amd64-3.6\Release\src/winrand.obj
    **error: command 'cl.exe' failed: No such file or directory**

**Comment by pburkart** [comment]
You may need to add cl.exe to your windows PATH variable

**Comment by bcbeatty** [comment]
I've added cl.exe to my path. 
I now get this issue:
```
creating build\temp.win-amd64-3.6\Release\src
  cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -Isrc/ -Isrc/inc-msvc/ -Ic:\users\beabri01\appdata\local\programs\python\python36\include -Ic:\users\beabri01\appdata\local\programs\python\python36\include "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" /Tcsrc/winrand.c /Fobuild\temp.win-amd64-3.6\Release\src/winrand.obj
  error: command 'cl.exe' failed: No such file or directory

  ----------------------------------------
  Failed building wheel for pycrypto
  Running setup.py clean for pycrypto
Failed to build pycrypto
Installing collected packages: pycrypto, paramiko, future
```

**Comment by pburkart** [comment]
Try reverting back to Python 3.5.2 if you're using 3.6+

Otherwise it may be an issue with your Visual C++ installation. Are you able to use the VS2015 developer console to perform these commands?

**Comment by cs-ark** [comment]
is cl.exe in `C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin` ? or whichever location you added to PATH

**Comment by jpribyl** [comment]
Hey guys, hope this helps someone.. it seems that this has not been updated in a while. You will probably need the latest version of paramiko (not the one that the package thinks you need) which you can get with:

```
pip install -U paramiko
```
The default ami is not longer great. I used the standard aws hvm ubuntu instance (although you'll have to ssh into it and install apache2-utils) Anyone who is stuck on this step feel free to reach out and I'll send you the bash script that I toiled over for the better part of a week. 

Additionally, if you are trying to use a .py then 
```
import bees
```
 will not work unless you copy bees.py from the package installation directory into your current directory. 

And, if you're anything like me then you may need to change line 446 of bees.py from 
```
    if basic_auth is not '':
```
to
```
    if basic_auth is not '' and basic_auth is not None:
```

good luck!

**Comment by bcbeatty** [comment]
I'm getting the following error on Windows 10:
$ pip install beeswithmachineguns
Collecting beeswithmachineguns
  Downloading https://files.pythonhosted.org/packages/6c/ca/981c61d8df4e7142bebc5332c4fe65cac07000add5237037efa0867c05bc/beeswithmachineguns-0.1.4.tar.gz
Collecting boto==2.0 (from beeswithmachineguns)
  Downloading https://files.pythonhosted.org/packages/79/e7/7bf7a14e797a53b2fa20ef359d38053318a95f29286864f5faa32a1dff66/boto-2.0.tar.gz (302kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\beabri01\AppData\Local\Temp\1\pip-install-yb__9y18\boto\setup.py", line 35, in <module>
        from boto import Version
      File "C:\Users\beabri01\AppData\Local\Temp\1\pip-install-yb__9y18\boto\boto\__init__.py", line 25, in <module>
        from boto.pyami.config import Config, BotoConfigLocations
      File "C:\Users\beabri01\AppData\Local\Temp\1\pip-install-yb__9y18\boto\boto\pyami\config.py", line 185
        print s.getvalue()
              ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\beabri01\AppData\Local\Temp\1\pip-install-yb__9y18\boto\

**Comment by jpribyl** [comment]
@bcbeatty this looks like a python2 / python3 issue to me.

python2 accepts print x
python3 requires print(x)

can you verify that you are using python3 for all of this? It looks like you're on windows.. I'm not a windows guy but on linux it would be something like which python or which pip. You may need to use pip3 install. I am on boto3 not boto2.

Also, I was unable to get the ~/.boto file to work, I had to add my aws keys as environment variables

**Comment by bcbeatty** [comment]
I'm using python 3.6, pip 18.0. 
I am running on windows 10, which I don't think uses boto, it uses a console in Administrator mode

**Comment by jpribyl** [comment]
@bcbeatty 
Can you try:
```
pip install boto3
```

or, if that fails installing from the github:
```
git clone git@github.com:boto/boto3.git
cd boto3
python setup.py install
```

**Comment by jpribyl** [comment]
Also, you should be using the most up to date version of bwmg. From the install instructions on their github page:
```
pip install https://github.com/newsapps/beeswithmachineguns/archive/master.zip
```
and not
```
pip install beeswithmachineguns
```

**Comment by bcbeatty** [comment]
@jpribyl  sorry that didn't seem to change the error. I tried both pip install and python setup.py

**Comment by bcbeatty** [comment]
I'm getting the following error with 
pip install https://github.com/newsapps/beeswithmachineguns/archive/master.zip 


[install.log](https://github.com/newsapps/beeswithmachineguns/files/2316205/install.log)
