### ISSUE TITLE
setup installation error

### ISSUE THREAD

**Issue by ighouri** [newsapps/beeswithmachineguns#229]
Hi,

I am getting below error when I am trying to pip install beeswithmachinesguns. I am unable to figure out this runtime auto conf error related to pycrypto. Can someone please assist ?

Here are my python and pip versions.
`
python --version
Python 3.6.5
pip --version
pip 19.0.3 from /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip (python 3.6)
`

**Installation Failure**
`
checking for gcc... gcc
    checking whether the C compiler works... no
    configure: error: in `/private/var/folders/fs/fghhw1dd55q4jt8vq9m5qcfnv5sy23/T/pip-install-4o_fqd0g/pycrypto':
    configure: error: C compiler cannot create executables
    See `config.log' for more details
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/fs/fghhw1dd55q4jt8vq9m5qcfnv5sy23/T/pip-install-4o_fqd0g/pycrypto/setup.py", line 456, in <module>
        core.setup(**kw)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/private/var/folders/fs/fghhw1dd55q4jt8vq9m5qcfnv5sy23/T/pip-install-4o_fqd0g/pycrypto/setup.py", line 251, in run
        self.run_command(cmd_name)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/private/var/folders/fs/fghhw1dd55q4jt8vq9m5qcfnv5sy23/T/pip-install-4o_fqd0g/pycrypto/setup.py", line 278, in run
        raise RuntimeError("autoconf error")
    RuntimeError: autoconf error
    
    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/fs/fghhw1dd55q4jt8vq9m5qcfnv5sy23/T/pip-install-4o_fqd0g/pycrypto/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/fs/fghhw1dd55q4jt8vq9m5qcfnv5sy23/T/pip-record-bzwfp3bs/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/fs/fghhw1dd55q4jt8vq9m5qcfnv5sy23/T/pip-install-4o_fqd0g/pycrypto/
`

**Comment by kylemcnee** [comment]
Was this ever solved?  Having the same issue.
