### ISSUE TITLE
when I run bees attack I got this error authentication methods available any help please 

### ISSUE THREAD

**Issue by temraz** [newsapps/beeswithmachineguns#231]
command => bees attack -n 100 -c 50 -u https://mywebsite.com
Read 1 bees from the roster: us-east-1d
Connecting to the hive.
Assembling bees.
Each of 1 bees will fire 100 rounds, 50 at a time.
Stinging URL sequentially so it will be cached for the attack.
Organizing the swarm.
Bee 0 is joining the swarm.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/beeswithmachineguns/bees.py", line 416, in _attack
    client.connect(params['instance_name'], username=params['username'])
  File "/home/ubuntu/.local/lib/python2.7/site-packages/paramiko/client.py", line 307, in connect
    look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/paramiko/client.py", line 520, in _auth
    raise SSHException('No authentication methods available')
SSHException: No authentication methods available

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/beeswithmachineguns/bees.py", line 799, in attack
    results = pool.map(_attack, params)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
SSHException: No authentication methods available

**Comment by iamtito** [comment]
upgrade paramiko by running this `pip install paramiko --upgrade` Also make sure you have your pem file in the right location(~/.ssh/filename.pem) and its in the aws key pairs(if not follow this step --> Security Groups>Key Pair>Import or creat Key Pair)
