### ISSUE TITLE
Bees not attacking at all, application fails

### ISSUE THREAD

**Issue by psypher246** [newsapps/beeswithmachineguns#74]
When using bees in a VPC I get this error when trying to attack:

Read 4 bees from the roster.
Connecting to the hive.
Assembling bees.
Each of 4 bees will fire 25 rounds, 2 at a time.
Stinging URL so it will be cached for the attack.
Organizing the swarm.
Bee 0 is joining the swarm.
Bee 1 is joining the swarm.
Bee 2 is joining the swarm.
Bee 3 is joining the swarm.
Traceback (most recent call last):
  File "/usr/local/bin/bees", line 6, in <module>
    main.main()
  File "/usr/local/lib/python2.7/dist-packages/beeswithmachineguns/main.py", line 163, in main
    parse_options()
  File "/usr/local/lib/python2.7/dist-packages/beeswithmachineguns/main.py", line 154, in parse_options
    bees.attack(options.url, options.number, options.concurrent, **additional_options)
  File "/usr/local/lib/python2.7/dist-packages/beeswithmachineguns/bees.py", line 510, in attack
    summarized_results = _summarize_results(results, params, csv_filename)
  File "/usr/local/lib/python2.7/dist-packages/beeswithmachineguns/bees.py", line 294, in _summarize_results
    complete_results = [r['complete_requests'] for r in summarized_results['complete_bees']]
TypeError: sequence index must be integer, not 'str'

When using bees outside a VPC I get this error when trying to attack:

Read 4 bees from the roster.
Connecting to the hive.
Assembling bees.
Each of 4 bees will fire 250 rounds, 25 at a time.
Stinging URL so it will be cached for the attack.
Organizing the swarm.
Bee 0 is joining the swarm.
Bee 1 is joining the swarm.
Bee 2 is joining the swarm.
Bee 3 is joining the swarm.
Traceback (most recent call last):
  File "/usr/local/bin/bees", line 6, in <module>
    main.main()
  File "/usr/local/lib/python2.7/dist-packages/beeswithmachineguns/main.py", line 163, in main
    parse_options()
  File "/usr/local/lib/python2.7/dist-packages/beeswithmachineguns/main.py", line 154, in parse_options
    bees.attack(options.url, options.number, options.concurrent, **additional_options)
  File "/usr/local/lib/python2.7/dist-packages/beeswithmachineguns/bees.py", line 510, in attack
    summarized_results = _summarize_results(results, params, csv_filename)
  File "/usr/local/lib/python2.7/dist-packages/beeswithmachineguns/bees.py", line 304, in _summarize_results
    summarized_results['mean_response'] = sum(complete_results) / summarized_results['num_complete_bees']
ZeroDivisionError: integer division or modulo by zero

Using latest bees from Git. This happens on Amazon Linux and Ubuntu with Python 2.6

Please let me know if I can test anything.

**Comment by sdillard** [comment]
I was having the same issue. When I reverted to python 2.6, it went away, so I believe this is an incompatibility with python 2.7.
