### ISSUE TITLE
Windows 8 - ImportError

### ISSUE THREAD

**Issue by PendragonDevelopment** [newsapps/beeswithmachineguns#79]
Not sure if this is a Windows/Python thing, but I figured I'd post my error - I get this when I try to attack my instance with bees:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\Python27\lib\multiprocessing\forking.py", line 380, in main
    prepare(preparation_data)
  File "c:\Python27\lib\multiprocessing\forking.py", line 489, in prepare
    file, path_name, etc = imp.find_module(main_name, dirs)
ImportError: No module named bees
```

Any suggestions? Other than move to *nix.

**Comment by PrasadBapatla** [comment]
having same error on Windows7; any suggestions?
