### ISSUE TITLE
Invalid availability zone: [us-east-1d]

### ISSUE THREAD

**Issue by analytically** [newsapps/beeswithmachineguns#90]
running: `bees up -s 4 -g public -k mykey`
but I get:

```
Connecting to the hive.
Attempting to call up 4 bees.
Traceback (most recent call last):
  File "/usr/local/bin/bees", line 5, in <module>
    main.main()
  File "/usr/local/lib/python2.7/dist-packages/beeswithmachineguns/main.py", line 127, in main
    parse_options()
  File "/usr/local/lib/python2.7/dist-packages/beeswithmachineguns/main.py", line 111, in parse_options
    bees.up(options.servers, options.group, options.zone, options.instance, options.login, options.key)
  File "/usr/local/lib/python2.7/dist-packages/beeswithmachineguns/bees.py", line 104, in up
    placement=zone)
  File "/usr/local/lib/python2.7/dist-packages/boto/ec2/connection.py", line 618, in run_instances
    return self.get_object('RunInstances', params, Reservation, verb='POST')
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 699, in get_object
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterValue</Code><Message>Invalid availability zone: [us-east-1d]</Message></Error></Errors><RequestID>7d01a404-48c7-4147-9774-f93c993e6b7a</RequestID></Response>
```

**Comment by sigsegved** [comment]
That still didnt fix for me. I tried 

[Boto]
ec2_region_name = ap-southeast-2
ec2_region_endpoint = ec2.ap-southeast-2.amazonaws.com

sudo bees up -s 1 -g public -k ec2-for-load-testing -z us-west-1

Traceback (most recent call last):
  File "/usr/local/bin/bees", line 5, in <module>
    main.main()
  File "/usr/local/lib/python2.7/dist-packages/beeswithmachineguns/main.py", line 127, in main
    parse_options()
  File "/usr/local/lib/python2.7/dist-packages/beeswithmachineguns/main.py", line 111, in parse_options
    bees.up(options.servers, options.group, options.zone, options.instance, options.login, options.key)
  File "/usr/local/lib/python2.7/dist-packages/beeswithmachineguns/bees.py", line 104, in up
    placement=zone)
  File "/usr/local/lib/python2.7/dist-packages/boto/ec2/connection.py", line 618, in run_instances
    return self.get_object('RunInstances', params, Reservation, verb='POST')
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 699, in get_object
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterValue</Code><Message>Invalid availability zone: [us-west-1]</Message></Error></Errors><RequestID>25392171-2a92-48bb-b734-577f26ef66f7</RequestID></Response>

**Comment by jozzhart** [comment]
@sigsegved I got it to work by also changing the zone argument to `-z ap-southeast-2b`

**Comment by danninux** [comment]
Hi All, 
That still didnt fix for me. I tried

[Boto]
ec2_region_name = ap-southeast-1
ec2_region_endpoint = ec2.ap-southeast-1.amazonaws.com

bees up -s 2 -k testing -z ap-southeast-1

Traceback (most recent call last):
  File "/usr/local/bin/bees", line 5, in <module>
    main.main()
  File "/usr/local/lib/python2.7/site-packages/beeswithmachineguns/main.py", line 127, in main
    parse_options()
  File "/usr/local/lib/python2.7/site-packages/beeswithmachineguns/main.py", line 111, in parse_options
    bees.up(options.servers, options.group, options.zone, options.instance, options.login, options.key)
  File "/usr/local/lib/python2.7/site-packages/beeswithmachineguns/bees.py", line 104, in up
    placement=zone)
  File "/usr/local/lib/python2.7/site-packages/boto/ec2/connection.py", line 618, in run_instances
    return self.get_object('RunInstances', params, Reservation, verb='POST')
  File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 699, in get_object
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterValue</Code><Message>Invalid availability zone: [ap-southeast-1]</Message></Error></Errors><RequestID>b8641ad4-6200-41dc-8d56-21e17e61e5c4</RequestID></Response>

Pls, anyone explain this ?
Thanks.

**Comment by mfrederickson** [comment]
@danninux even though I have the zone without the trailing letter in my .boto file, I still had to use the letter when starting up my bees:  ` -z us-west-2a `.

```
[Boto]
ec2_region_name=us-west-2
```

**Comment by danninux** [comment]
@mfrederickson I already tried, but still didn't fix for me.
[Boto]
ec2_region_name = ap-southeast-1

$ bees up -s 2 -k test -z ap-southeast-1a

Traceback (most recent call last):
  File "/usr/local/bin/bees", line 5, in <module>
    main.main()
  File "/usr/local/lib/python2.7/site-packages/beeswithmachineguns/main.py", line 127, in main
    parse_options()
  File "/usr/local/lib/python2.7/site-packages/beeswithmachineguns/main.py", line 111, in parse_options
    bees.up(options.servers, options.group, options.zone, options.instance, options.login, options.key)
  File "/usr/local/lib/python2.7/site-packages/beeswithmachineguns/bees.py", line 104, in up
    placement=zone)
  File "/usr/local/lib/python2.7/site-packages/boto/ec2/connection.py", line 618, in run_instances
    return self.get_object('RunInstances', params, Reservation, verb='POST')
  File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 699, in get_object
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterValue</Code><Message>Invalid availability zone: [ap-southeast-1a]</Message></Error></Errors><RequestID>b4552b5c-4fad-4260-a6b4-41581fbb4148</RequestID></Response>

**Comment by danninux** [comment]
Done, thanks @mfrederickson
