### ISSUE TITLE
attack erroring out

### ISSUE THREAD

**Issue by lcc2207** [newsapps/beeswithmachineguns#97]
the main controller is ubuntu 14.04.

Read 3 bees from the roster.
Connecting to the hive.
Assembling bees.
Each of 3 bees will fire 333 rounds, 33 at a time.
Stinging URL so it will be cached for the attack.
Organizing the swarm.
Bee 0 is joining the swarm.
Bee 2 is joining the swarm.
Bee 1 is joining the swarm.
Traceback (most recent call last):
  File "./bees", line 6, in <module>
    main.main()
  File "/root/beeswithmachineguns/beeswithmachineguns/main.py", line 170, in main
    parse_options()
  File "/root/beeswithmachineguns/beeswithmachineguns/main.py", line 161, in parse_options
    bees.attack(options.url, options.number, options.concurrent, **additional_options)
  File "/root/beeswithmachineguns/beeswithmachineguns/bees.py", line 529, in attack
    summarized_results = _summarize_results(results, params, csv_filename)
  File "/root/beeswithmachineguns/beeswithmachineguns/bees.py", line 305, in _summarize_results
    complete_results = [r['complete_requests'] for r in summarized_results['complete_bees']]
TypeError: sequence index must be integer, not 'str'

**Comment by jesseadams** [comment]
:+1: I have this exact same issue.

**Comment by leonardothibes** [comment]
Me too
